
baseURL = 'https://homework.quest/'
languageCode = 'en-us'
title = 'Learning resources from Prof. Nat Tuck'
theme = 'congo'

defaultContentLanguage = "en"
enableRobotsTXT = true
#paginate = 10
summaryLength = 0
enableGitInfo = true

staticDir = ['static']

[outputs]
home = ["HTML", "RSS", "JSON"]


[pagination]
pagerSize = 10